### ISSUE TITLE
Should the version roll forward given a version in the form X.Y.*?

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core-runtime#135]
## What happened?

* What were you attempting to do?

`pack build` an app that contains `<RuntimeFrameworkVersion>2.0.*</RuntimeFrameworkVersion>` in the csproj file.

* What did you expect to happen?

The version to roll forward and the buildpack selects supported runtime version 2.1. We feel like this warrants a roll forward.

* What was the actual behavior? Please provide log output, if possible.

```
    Candidate version sources (in priority order):
      console.csproj -> "2.0.*"
      <unknown>      -> "*"
      <unknown>      -> "*"
      <unknown>      -> "*"

failed to satisfy "dotnet-runtime" dependency for stack "io.buildpacks.stacks.bionic" with version constraint "2.0.*": no compatible versions. Supported versions are: [2.1.23, 2.1.24, 3.1.10, 3.1.11, 5.0.1, 5.0.2]
ERROR: failed to build: exit status 1
```
 It seems the current implementation only rolls forward if the version is `x.y.z`, and will not if it contains a `*`. We should revisit if this is the best solution?

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

dotnet-core-runtime buildpack 0.1.3

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

paketo-buildpacks/full

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

https://github.com/cloudfoundry/dotnet-core-buildpack/tree/v2.3.22/fixtures/console_app

## Checklist

* [X] I have included log output.
* [X] The log output includes an error message.
* [X] I have included steps for reproduction.

**Comment by TisVictress** [comment]
@paketo-buildpacks/dotnet-core-maintainers Was there ever a decision on whether we should implement this feature?

**Comment by fg-j** [comment]
I think our decision should be based on whatever policy the dotnet CLI itself uses. I can take on looking into it.

**Comment by fg-j** [comment]
From what I can tell in the [.NET documentation](https://docs.microsoft.com/en-us/dotnet/core/versions/selection) about version selection, you can use `RuntimeFrameworkVersion` to "override the minimum runtime patch version (to higher or lower versions) in the project file". Since `RuntimeFrameworkVersion` sets the _minimum_ runtime patch version, I think the version _should_ roll forward even when it includes a wildcard.
