### ISSUE TITLE
Restructure: Only provide the dotnet-runtime dependency 

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/dotnet-core-runtime#84]
### Background

This buildpack currently provides the `dotnet-runtime` dependency, which
* ~Puts the `dotnet` cli on the path.~ This responsibility was moved to `dotnet-sdk`
* Provides a library of shared `dll` files needed to run dotnet apps

It always requires itself on launch, which is unnecessary because in order to run `dotnet-core` apps, you can either run them with the `dotnet run` command, or compile them with the `dotnet publish` command, and then run the binary directly. Thus, it is unnecessary to always put the `dotnet` cli in the final launch image.

### Proposal

In order to conform the the [restructure rfc](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0001-restructure.md), this buildpack should provide the `dotnet-runtime` dependency and require nothing. This will greatly simplify its interaction with other buildpacks in the language family.

The builldpack should Install a specified version of the `dotnet` command line tool and make it available on the `$PATH`

The buildpack should also be rewritten in a `packit` compliant way.

**Comment by ForestEckhardt** [comment]
Some quick notes:
- `detect` should always provide `dotnet-runtime` and require it if there is an entry in `buildpack.yml`.
- The current logic in `build` should be simplified to mimic that of our other provision buildpacks. We should priority sort, find a compatible version (if one exists), and install that version. Leave the failure to `dotnet-publish` or when the container is run.

Priority Order:
1. `buildpack.yml`
1. `*.*sproj`

**Comment by sophiewigmore** [comment]
See Framework-dependent apps roll forward section of: https://docs.microsoft.com/en-us/dotnet/core/versions/selection.
Priority sort mentioned by Forest in the comment above will replace the [BuildpackYAMLVersionCheck](https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/0dde652b58ba7ebb34a5501b1341946bd76168e3/runtime/versioning.go#L11).

**Comment by joshzarrabi** [comment]
# Acceptance

### First we have to build the app

```bash
$ cd app
$ ls
plan.toml

$ cat plan.toml
[[requires]]
  name = "dotnet-runtime"

  [requires.metadata]
    launch = true

$ pack build my-app -b <path to built buildpack> -b gcr.io/paketo-community/build-plan
```


### Then we check that we only require the `dotnet-core-runtime` dependency

```bash
$ ls /layers
config  paketo-buildpacks_dotnet-core-runtime
```

### Then check that we symlink the dll libraries to `$DOTNET_ROOT`

```bash
$ ls -la $DOTNET_ROOT/shared/
total 12
drwxr-xr-x 2 cnb cnb 4096 Jan  1  1980 .
drwxr-xr-x 3 cnb cnb 4096 Jan  1  1980 ..
lrwxrwxrwx 1 cnb cnb   94 Jan  1  1980 Microsoft.NETCore.App -> /layers/paketo-buildpacks_dotnet-core-runtime/dotnet-core-runtime/shared/Microsoft.NETCore.App
```

```bash
$ ls $DOTNET_ROOT/shared/Microsoft.NETCore.App/5.0.1/
Microsoft.CSharp.dll                            System.Dynamic.Runtime.dll              System.Net.WebClient.dll                               System.Runtime.Serialization.Primitives.dll        System.ValueTuple.dll 
...............................................
```


## Now lets check that we require the correct version if a `buildpack.yml` specifies a version

### Build the app
```
$ cd new_app
$ ls
buildpack.yml plan.toml

$ cat buildpack.yml
---
dotnet-framework:
  version: "2.1.22"

$ pack build my-app -b <path to built buildpack> -b gcr.io/paketo-community/build-plan
```

### Now check to make sure the correct version is included

```
$ ls $DOTNET_ROOT/shared/Microsoft.NETCore.App
2.1.22
```

### Make sure the `${RUNTIME_VERSION}` env variable is set

```
$ cat /layers/paketo-buildpacks_dotnet-core-runtime/dotnet-core-runtime/env.build/RUNTIME_VERSION.override
2.1.22
```

So, I can accept the story as completed.

**Comment by fg-j** [comment]
afaik, we had explicitly decided *not* to roll forward the version of the runtime when a version is specified in the `buildpack.yml` (as implied by [this unit test for the version resolver](https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/e262e7c0769f4dfd53c95917c0c0b8bf37acb11a/runtime_version_resolver_test.go#L236). Not sure if this decision was documented elsewhere, maybe in Slack or in some sort of one-pager? @ForestEckhardt Am I remembering this correctly?

**Comment by joshzarrabi** [comment]
Resolved that the buildpack.yml will cancel out roll forward logic.
